/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dsss/chip_sync_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(auto)                                                 */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/dsss/chip_sync_c.h>

void bind_chip_sync_c(py::module& m)
{
    using chip_sync_c = gr::ieee80211::chip_sync_c;

    py::class_<chip_sync_c, gr::block, gr::basic_block,
        std::shared_ptr<chip_sync_c>>(m, "chip_sync_c",
        "802.11b DSSS/CCK chip synchronization and packet receiver.\n\n"
        "This block performs correlation-based synchronization on incoming DSSS/CCK\n"
        "signals, demodulates the symbols, and outputs complete packets via message port.\n\n"
        "Supports all 802.11b data rates:\n"
        "  - 1 Mbps (DBPSK with Barker spreading)\n"
        "  - 2 Mbps (DQPSK with Barker spreading)\n"
        "  - 5.5 Mbps (CCK with 4-bit encoding)\n"
        "  - 11 Mbps (CCK with 8-bit encoding)\n\n"
        "Features:\n"
        "  - Barker code correlation for packet detection\n"
        "  - Phase-locked loop for carrier tracking\n"
        "  - Automatic rate detection from SIGNAL field\n"
        "  - PLCP header CRC validation\n"
        "  - Both long and short preamble support")

        .def(py::init(&chip_sync_c::make),
            py::arg("long_preamble"),
            py::arg("threshold"),
            "Create chip synchronization block.\n\n"
            "Args:\n"
            "    long_preamble (bool): True for long preamble, False for short preamble\n"
            "    threshold (float): Correlation threshold for packet detection (0.0-11.0)\n\n"
            "Returns:\n"
            "    chip_sync_c: Shared pointer to chip sync block")

        .def("set_preamble_type", &chip_sync_c::set_preamble_type,
            py::arg("islong"),
            "Set preamble type.\n\n"
            "Args:\n"
            "    islong (bool): True for long preamble, False for short preamble");
}
