/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dsss/ppdu_chip_mapper_bc.h)                                */
/* BINDTOOL_HEADER_FILE_HASH(21d5d04519da1b0cdfd365587143b1e2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/dsss/ppdu_chip_mapper_bc.h>

void bind_ppdu_chip_mapper_bc(py::module& m)
{
    using ppdu_chip_mapper_bc = gr::ieee80211::ppdu_chip_mapper_bc;

    py::class_<ppdu_chip_mapper_bc, gr::block, gr::basic_block,
        std::shared_ptr<ppdu_chip_mapper_bc>>(m, "ppdu_chip_mapper_bc",
        "802.11b DSSS/CCK chip mapper and modulator.\n\n"
        "This block converts bytes to complex chip sequences for all 802.11b modulation\n"
        "schemes. It reads bytes from the input stream and generates the appropriate\n"
        "chip sequences based on the selected data rate.\n\n"
        "Modulation schemes:\n"
        "  - 1 Mbps: DBPSK with 11-chip Barker spreading\n"
        "  - 2 Mbps: DQPSK with 11-chip Barker spreading\n"
        "  - 5.5 Mbps: CCK with 4-bit encoding (4 codes)\n"
        "  - 11 Mbps: CCK with 8-bit encoding (64 codes)\n\n"
        "Features:\n"
        "  - Automatic rate detection from stream tags\n"
        "  - Barker code generation for DSSS\n"
        "  - CCK code generation for high-rate modes\n"
        "  - Differential phase encoding\n"
        "  - Support for both long and short preambles")

        .def(py::init(&ppdu_chip_mapper_bc::make),
            py::arg("length_tag_name"),
            "Create PPDU chip mapper block.\n\n"
            "Args:\n"
            "    length_tag_name (str): Name of stream tag containing packet length\n\n"
            "Returns:\n"
            "    ppdu_chip_mapper_bc: Shared pointer to chip mapper block");
}
