/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dsss/ppdu_prefixer.h)                                      */
/* BINDTOOL_HEADER_FILE_HASH(auto)                                                 */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee80211/dsss/ppdu_prefixer.h>

void bind_ppdu_prefixer(py::module& m)
{
    using ppdu_prefixer = gr::ieee80211::ppdu_prefixer;

    py::class_<ppdu_prefixer, gr::block, gr::basic_block,
        std::shared_ptr<ppdu_prefixer>>(m, "ppdu_prefixer",
        "802.11b PPDU prefixer - adds PLCP preamble and header.\n\n"
        "This message-driven block receives PSDU (MAC frame) messages and prepends\n"
        "the appropriate PLCP preamble and header according to IEEE 802.11b specification.\n\n"
        "PLCP Components:\n"
        "  - SYNC: Long preamble (144 bits) or short preamble (72 bits)\n"
        "  - SFD: Start Frame Delimiter (0xF3A0 long, 0x05CF short)\n"
        "  - SIGNAL: Data rate indicator (0x0A, 0x14, 0x37, 0x6E)\n"
        "  - SERVICE: Service field with length extension for 11 Mbps\n"
        "  - LENGTH: PSDU length in microseconds\n"
        "  - CRC-16: Header error detection\n\n"
        "Features:\n"
        "  - 7-bit LFSR scrambling (polynomial x^7 + x^4 + 1)\n"
        "  - Automatic length calculation for each rate\n"
        "  - CRC-16 header protection\n"
        "  - Support for all 7 rate/preamble combinations")

        .def(py::init(&ppdu_prefixer::make),
            py::arg("rate"),
            "Create PPDU prefixer block.\n\n"
            "Args:\n"
            "    rate (int): 802.11b rate/preamble configuration:\n"
            "                0 = 1 Mbps long preamble\n"
            "                1 = 2 Mbps long preamble\n"
            "                2 = 5.5 Mbps long preamble\n"
            "                3 = 11 Mbps long preamble\n"
            "                4 = 2 Mbps short preamble\n"
            "                5 = 5.5 Mbps short preamble\n"
            "                6 = 11 Mbps short preamble\n\n"
            "Returns:\n"
            "    ppdu_prefixer: Shared pointer to PPDU prefixer block")

        .def("get_rate", &ppdu_prefixer::get_rate,
            "Get current rate configuration.\n\n"
            "Returns:\n"
            "    int: Current rate/preamble setting");
}
